### ISSUE TITLE
Can't establish a connection to the websocket server

### ISSUE THREAD

**Issue by EddyLuten** [EddyLuten/mkdocs-live-edit-plugin#2]
I have the similar problem. The Edit button not responding.

![image](https://github.com/EddyLuten/mkdocs-live-edit-plugin/assets/1875345/f0197548-d2f2-46a1-8f8e-aa7830f539e1)

![image](https://github.com/EddyLuten/mkdocs-live-edit-plugin/assets/1875345/6b1d1123-47ee-40eb-a064-9095352f8e75)

![image](https://github.com/EddyLuten/mkdocs-live-edit-plugin/assets/1875345/2147bdd0-4714-4501-b374-b01a95178c7b)

_Originally posted by @noeldum in https://github.com/EddyLuten/mkdocs-live-edit-plugin/issues/1#issuecomment-1917833379_

**Comment by EddyLuten** [comment]
I'm unable to reproduce this locally. I'll leave this open in case anyone can supply me with some more information on how to repro or fix this.

**Comment by noeldum** [comment]
Using Ubuntu 22.04.3 LTS

**Comment by EddyLuten** [comment]
Hmm, I'm on Ubuntu 23.10 using Firefox 122.0. I was on 22.04.3 LTS until a few days ago and also didn't have any of these issues.

I don't have netstat, but when I run `ss -ap | grep 8484 | sed 's/[[:space:]]*$//'` I get this output:

![image](https://github.com/EddyLuten/mkdocs-live-edit-plugin/assets/1082806/a9ed2d14-2c6b-4554-aab2-f45762f656a1)

Everything seems to be working as expected; there are no browser console errors, etc. Could you try overriding the websocket port and see if you still see the same error? You can do so by modifying your mkdocs.yml like so:

![image](https://github.com/EddyLuten/mkdocs-live-edit-plugin/assets/1082806/5bdf1e1f-7a87-4a09-94e6-d0dd3069fdde)

Where 8833 is any port you want that your process is allowed to open.

**Comment by noeldum** [comment]
same thing again. No change.

![image](https://github.com/EddyLuten/mkdocs-live-edit-plugin/assets/1875345/56fb6985-2d01-4c01-ba01-0b3efce6a1e1)

**Comment by EddyLuten** [comment]
Interesting. I don't see FF as a consumer of that connection in your screenshot at all. Can you verify that you don't see any issues when [running a test here](https://websocketstest.com/)?

Also, do you happen to have another browser installed to see if it works there?

**Comment by noeldum** [comment]
all ticked green on websocketstests. Both using firefox and chromium. Both browsers behave the same.

**Comment by EddyLuten** [comment]
What might be happening is that the WebSocket tries to connect before it completes initializing on the server. I'm making a few improvements in 0.1.4 to connect after DOM loading is complete and a retry mechanism if the connection fails. I also won't show the controls until I get a signal from the server that the WebSocket connection is open and ready to accept connections.

Let me know if the issue persists in this new version, and I'll keep digging around.

**Comment by EddyLuten** [comment]
Can't repro this after almost a year. Closing until there are clear steps.

**Comment by noeldum** [comment]
I gave up using the plugin.
